name: macroscope
channels:
  - conda-forge
  - defaults
dependencies:
  - jsonschema=4.18.2
  - kivy=2.2.1
  - matplotlib=3.7.2
  - nbconvert=7.6.0
  - nbformat=5.9.1
  - notebook=6.5.4
  - numpy=1.25.1
  - opencv=4.7.0
  - pillow=10.0.0
  - pip=23.1.2
  - python=3.10.12
  - scikit-image=0.21.0
  - scipy=1.11.1
  - zaber-motion=4.2.0
  - pip:
    - pypylon==2.2.0
    - itk-elastix

