# title: 
description: A minimal websites presenting the macroscopes we created/worked with in Scholz Lab
theme: just-the-docs
url: https://scholz-lab.github.io/glowtracker
logo: "custom_assets/images/macroscope_logo.png"
# favicon_ico: "custom_assets/images/favicon.ico"

aux_links:
  "GlowTracker on GitHub":
    - "https://github.com/scholz-lab/GlowTracker"
