source 'https://rubygems.org'

gem "jekyll", "~> 4.3.0"
gem 'jekyll-sass-converter', '~> 3.1.0'
gem "just-the-docs", "~> 0.7.0"
gem "csv"
gem "base64"
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
gem "fiddle"