# Publish package to PyPI and TestPyPI
name: Publish GlowTracker

# Tell GitHub when to run the action
on:
  # This will run every time a new release is published
  release:
    types: [published]
  # This workflow is triggered on push events only for the master branch
  push:
    branches: [ master ]
  # This workflow can also be manually started from the Actions tab in GitHub
  # Used also for manual testing on the publish-package branch
  workflow_dispatch:
    branches: [ master, publish-package ]

# The publish workflow consist currently only on one job
jobs:
  publish:
    # Run the workflow on the latest Ubuntu version
    runs-on: ubuntu-latest
    permissions:
      id-token: write # NOTE: this permission is mandatory for trusted publishing
    steps:
      # Checkout the repository
      - name: Checkout glowtracker
        uses: actions/checkout@v3
      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      # Updating pip and installing 'build'.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install --upgrade build
      # Creating package wheel and a .tar.gz source distribution.
      - name: Build package
        run: >-
          python -m build
          --sdist
          --wheel
          ${{ github.workspace }}
      # Publish to TestPyPI using Trusted Publisher (GitHub)
      # REF: https://docs.pypi.org/trusted-publishers/using-a-publisher/
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      # Publish to PyPI using Trusted Publisher (GitHub)
      # REF: https://docs.pypi.org/trusted-publishers/using-a-publisher/
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1